- id: shellcheck
  name: ShellCheck
  description: Static analysis tool for shell scripts
  entry: pre-commit-hooks/shellcheck.sh
  language: script
  exclude: \.jinja$

- id: tf-format
  name: TfFormat
  description: Terraform / OpenTofu .tf format
  entry: pre-commit-hooks/tf-format.sh
  language: script
  files: '\.(?:tf|tofu|tfvars|tftest\.hcl|tofutest\.hcl)$'
  pass_filenames: true
